sales:  # 销售管理
  login:
    url: /api/auth_center/v3/login  # 登录
    name: 登录  # 接口注释
    className: TestLogin_sales  # 接口类名
    funName:
      - test_login_sales: {  # 接口方法名
      bar: [{'account': 13718411099, password: Li123456, company_id: 43451}],  # 接口参数
      test_data: {},
      case_name: 正常登录,
      result: ['0'],  # 预期结果
      mode: post,  # 请求类型
      re_bar: data, # 请求参数
      }
  documents:
    url: /api/scrm/documents  # 接口地址
    name: 获取相关文档  # 接口注释
    className: Documents_sales  # 接口类名
    funName:
      - test_documents_send: {  # 接口方法名
      bar: {'type': 1, 'source': 0},  # 接口参数
      test_data: {},
      case_name: 类型为客户，来源为发出去,
      result: [0],  # 预期结果
      mode: post,  # 请求类型
      re_bar: data, # 请求参数
      }
        test_documents_show: {  # 接口方法名
        bar: {'type': 1, 'source': 1},  # 接口参数
        test_data: {},
        case_name: 类型为客户，来源为收到的,
        result: [0],  # 预期结果
        mode: post,  # 请求类型
        re_bar: data, # 请求参数
        }
        test_documents_contacts: {  # 接口方法名
        bar: {'type': 0, 'source': 0},  # 接口参数
        test_data: {},
        case_name: 类型为联系人、来源为发出去,
        result: [0],  # 预期结果
        mode: post,  # 请求类型
        re_bar: data, # 请求参数
        }
  actionsList:
    url: /api/scrm/actionsList  # 新增联系人
    name: 联系人  # 接口注释
    className: actionsList_sales  # 接口类名
    funName:
      - test_actionsList: {  # 接口方法名
      bar: {contacts_id: , start_time: '2018-08-23',  system_type: scrm, end_time: '2018-09-21',},  # 接口参数
      test_data: [/api/scrm/contactAdd, {"email":"","mobile":"13713733833","phone":"","first_name":"","last_name":"","position":"","customer_id":"","life_cycle":"1","salesman":"100082755"}], # 前置条件
      case_name: 新增联系人、行为记录, # 用例注释
      result: [0],  # 预期结果
      mode: post,  # 请求类型
      re_bar: data, # 请求参数
      }
